### ISSUE TITLE
Spain not wokring

### ISSUE THREAD

**Issue by zpelechova** [apify/covid-19#147]

**Comment by laidihalim** [comment]
@zpelechova & @remyoucef, The previous source shows only weekly data. I found this  official and daily updated pdf source:
https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_142_COVID-19.pdf
Source page:
https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/situacionActual.htm

**Comment by zpelechova** [comment]
Hi, we are discussing it internally if it is worth to scrape the pdf, I will let you know. Thanks.

**Comment by zpelechova** [comment]
Would it be possible to add the regions as well - to keep the format of the saved data?
