### ISSUE TITLE
Total us cases and deaths are not available we are getting null 

### ISSUE THREAD

**Issue by muaaztausif** [apify/covid-19#162]
i am using blow link to get Covid-19 data into my side. it was working fine but from yesterday i am not getting total cases and deaths. I am also posting the result taken at Sunday, June 28, 2020

https://api.apify.com/v2/key-value-stores/moxA3Q0aZh5LosewB/records/LATEST?disableRedirect=true

{
  "totalCases": null,
  "totalDeaths": null,
  "casesByState": [
    {
      "name": "Alabama",
      "range": "20,001 to 40,000",
      "casesReported": 34220
    },
    {
      "name": "Alaska",
      "range": "0 to 1,000",
      "casesReported": 836
    },
    {
      "name": "American Samoa",
      "range": "0 to 1,000",
      "casesReported": 0
    },
    {
      "name": "Arizona",
      "range": "40,001 or more",
      "casesReported": 66458
    },
    {
      "name": "Arkansas",
      "range": "10,001 to 20,000",
      "casesReported": 18740
    },
    {
      "name": "California",
      "range": "40,001 or more",
      "casesReported": 200461
    },
    {
      "name": "Colorado",
      "range": "20,001 to 40,000",
      "casesReported": 31796
    },
    {
      "name": "Connecticut",
      "range": "40,001 or more",
      "casesReported": 46059
    },
    {
      "name": "Delaware",
      "range": "10,001 to 20,000",
      "casesReported": 11107
    },
    {
      "name": "District of Columbia",
      "range": "10,001 to 20,000",
      "casesReported": 10185
    },
    {
      "name": "Florida",
      "range": "40,001 or more",
      "casesReported": 120574
    },
    {
      "name": "Georgia",
      "range": "40,001 or more",
      "casesReported": 72995
    },
    {
      "name": "Guam",
      "range": "0 to 1,000",
      "casesReported": 247
    },
    {
      "name": "Hawaii",
      "range": "0 to 1,000",
      "casesReported": 796
    },
    {
      "name": "Idaho",
      "range": "5,001 to 10,000",
      "casesReported": 5148
    },
    {
      "name": "Illinois",
      "range": "40,001 or more",
      "casesReported": 141344
    },
    {
      "name": "Indiana",
      "range": "40,001 or more",
      "casesReported": 44140
    },
    {
      "name": "Iowa",
      "range": "20,001 to 40,000",
      "casesReported": 27685
    },
    {
      "name": "Kansas",
      "range": "10,001 to 20,000",
      "casesReported": 13538
    },
    {
      "name": "Kentucky",
      "range": "10,001 to 20,000",
      "casesReported": 14859
    },
    {
      "name": "Louisiana",
      "range": "40,001 or more",
      "casesReported": 54769
    },
    {
      "name": "Maine",
      "range": "1,001 to 5,000",
      "casesReported": 3102
    },
    {
      "name": "Marshall Islands",
      "range": "0 to 1,000",
      "casesReported": 0
    },
    {
      "name": "Maryland",
      "range": "40,001 or more",
      "casesReported": 66450
    },
    {
      "name": "Massachusetts",
      "range": "40,001 or more",
      "casesReported": 108070
    },
    {
      "name": "Michigan",
      "range": "40,001 or more",
      "casesReported": 69329
    },
    {
      "name": "Micronesia",
      "range": "0 to 1,000",
      "casesReported": 0
    },
    {
      "name": "Minnesota",
      "range": "20,001 to 40,000",
      "casesReported": 34616
    },
    {
      "name": "Mississippi",
      "range": "20,001 to 40,000",
      "casesReported": 25531
    },
    {
      "name": "Missouri",
      "range": "10,001 to 20,000",
      "casesReported": 19914
    },
    {
      "name": "Montana",
      "range": "0 to 1,000",
      "casesReported": 852
    },
    {
      "name": "Nebraska",
      "range": "10,001 to 20,000",
      "casesReported": 18524
    },
    {
      "name": "Nevada",
      "range": "10,001 to 20,000",
      "casesReported": 15472
    },
    {
      "name": "New Hampshire",
      "range": "5,001 to 10,000",
      "casesReported": 5638
    },
    {
      "name": "New Jersey",
      "range": "40,001 or more",
      "casesReported": 170584
    },
    {
      "name": "New Mexico",
      "range": "10,001 to 20,000",
      "casesReported": 11408
    },
    {
      "name": "New York",
      "range": "40,001 or more",
      "casesReported": 177150
    },
    {
      "name": "New York City",
      "range": "40,001 or more",
      "casesReported": 215891
    },
    {
      "name": "North Carolina",
      "range": "40,001 or more",
      "casesReported": 58818
    },
    {
      "name": "North Dakota",
      "range": "1,001 to 5,000",
      "casesReported": 3421
    },
    {
      "name": "Northern Marianas",
      "range": "0 to 1,000",
      "casesReported": 30
    },
    {
      "name": "Ohio",
      "range": "40,001 or more",
      "casesReported": 48638
    },
    {
      "name": "Oklahoma",
      "range": "10,001 to 20,000",
      "casesReported": 11975
    },
    {
      "name": "Oregon",
      "range": "5,001 to 10,000",
      "casesReported": 7818
    },
    {
      "name": "Palau",
      "range": "0 to 1,000",
      "casesReported": 0
    },
    {
      "name": "Pennsylvania",
      "range": "40,001 or more",
      "casesReported": 84991
    },
    {
      "name": "Puerto Rico",
      "range": "5,001 to 10,000",
      "casesReported": 7066
    },
    {
      "name": "Rhode Island",
      "range": "10,001 to 20,000",
      "casesReported": 16661
    },
    {
      "name": "South Carolina",
      "range": "20,001 to 40,000",
      "casesReported": 30335
    },
    {
      "name": "South Dakota",
      "range": "5,001 to 10,000",
      "casesReported": 6535
    },
    {
      "name": "Tennessee",
      "range": "20,001 to 40,000",
      "casesReported": 39444
    },
    {
      "name": "Texas",
      "range": "40,001 or more",
      "casesReported": 137624
    },
    {
      "name": "Utah",
      "range": "20,001 to 40,000",
      "casesReported": 20481
    },
    {
      "name": "Vermont",
      "range": "1,001 to 5,000",
      "casesReported": 1198
    },
    {
      "name": "Virgin Islands",
      "range": "0 to 1,000",
      "casesReported": 81
    },
    {
      "name": "Virginia",
      "range": "40,001 or more",
      "casesReported": 61247
    },
    {
      "name": "Washington",
      "range": "20,001 to 40,000",
      "casesReported": 30855
    },
    {
      "name": "West Virginia",
      "range": "1,001 to 5,000",
      "casesReported": 2730
    },
    {
      "name": "Wisconsin",
      "range": "20,001 to 40,000",
      "casesReported": 29668
    },
    {
      "name": "Wyoming",
      "range": "1,001 to 5,000",
      "casesReported": 1368
    }
  ],
  "sourceUrl": "https://www.cdc.gov/coronavirus/2019-ncov/cases-in-us.html",
  "lastUpdatedAtSource": "2020-06-28T00:00:00.000Z",
  "lastUpdatedAtApify": "2020-06-28T10:50:00.000Z",
  "readMe": "https://apify.com/petrpatek/covid-usa-cdc"
}

**Comment by zpelechova** [comment]
Hey, thanks for reporting, it's fixed now.

**Comment by muaaztausif** [comment]
yeah its fixed Thanks alot
