### ISSUE TITLE
The deceased property value of index Philippines was replaced by total number of cases 

### ISSUE THREAD

**Issue by DavidBroke** [apify/covid-19#174]
{
  "infected": 47873,
  "tested": "N/A",
  "recovered": 12386,
  "deceased": 1309,
  "country": "Philippines",
  "historyData": "https://api.apify.com/v2/datasets/sFSef5gfYg3soj8mb/items?format=json&clean=1",
  "sourceUrl": "http://www.covid19.gov.ph/",
  "lastUpdatedAtApify": "2020-07-07T13:10:00.000Z",
  "lastUpdatedAtSource": "2020-07-07T08:00:00.000Z",
  "readMe": "https://apify.com/katerinahronik/covid-philippines"
},
{
  "infected": 50359,
  "tested": "N/A",
  "recovered": 12588,
  "deceased": 1314,
  "country": "Philippines",
  "historyData": "https://api.apify.com/v2/datasets/sFSef5gfYg3soj8mb/items?format=json&clean=1",
  "sourceUrl": "http://www.covid19.gov.ph/",
  "lastUpdatedAtApify": "2020-07-08T13:50:00.000Z",
  "lastUpdatedAtSource": "2020-07-08T08:00:00.000Z",
  "readMe": "https://apify.com/katerinahronik/covid-philippines"
},
{
  "infected": 36547,
  "tested": "N/A",
  "recovered": 12588,
  "deceased": 50359,
  "country": "Philippines",
  "historyData": "https://api.apify.com/v2/datasets/sFSef5gfYg3soj8mb/items?format=json&clean=1",
  "sourceUrl": "http://www.covid19.gov.ph/",
  "lastUpdatedAtApify": "2020-07-09T09:25:00.000Z",
  "lastUpdatedAtSource": "2020-07-08T08:00:00.000Z",
  "readMe": "https://apify.com/katerinahronik/covid-philippines"
},
{
  "infected": 37627,
  "tested": "N/A",
  "recovered": 12813,
  "deceased": 51754,
  "country": "Philippines",
  "historyData": "https://api.apify.com/v2/datasets/sFSef5gfYg3soj8mb/items?format=json&clean=1",
  "sourceUrl": "http://www.covid19.gov.ph/",
  "lastUpdatedAtApify": "2020-07-09T14:10:00.000Z",
  "lastUpdatedAtSource": "2020-07-09T08:00:00.000Z",
  "readMe": "https://apify.com/katerinahronik/covid-philippines"
},
{
  "infected": 38324,
  "tested": "N/A",
  "recovered": 13230,
  "deceased": 52914,
  "country": "Philippines",
  "historyData": "https://api.apify.com/v2/datasets/sFSef5gfYg3soj8mb/items?format=json&clean=1",
  "sourceUrl": "http://www.covid19.gov.ph/",
  "lastUpdatedAtApify": "2020-07-10T13:10:00.000Z",
  "lastUpdatedAtSource": "2020-07-10T08:00:00.000Z",
  "readMe": "https://apify.com/katerinahronik/covid-philippines"
},
{
  "infected": 38813,
  "tested": "N/A",
  "recovered": 14037,
  "deceased": 54222,
  "country": "Philippines",
  "historyData": "https://api.apify.com/v2/datasets/sFSef5gfYg3soj8mb/items?format=json&clean=1",
  "sourceUrl": "http://www.covid19.gov.ph/",
  "lastUpdatedAtApify": "2020-07-11T09:25:00.000Z",
  "lastUpdatedAtSource": "2020-07-10T08:00:00.000Z",
  "readMe": "https://apify.com/katerinahronik/covid-philippines"
}

**Comment by laidihalim** [comment]
Thank you for the feedback, we're working on it.

**Comment by zpelechova** [comment]
Thanks @DavidBroke for pointing out and @laidihalim for fixing it! Zuzka
