### ISSUE TITLE
Czechia:infectedByRegion is missing

### ISSUE THREAD

**Issue by stepanex** [apify/covid-19#179]
commented out in commit https://github.com/apify/covid-19/commit/49e5954651d75ab5b54b3e7c33c2aecaecd6f823#diff-67daba7c73d511c1edd63cff8da03c33

**Comment by stepanex** [comment]
the 'infectedByRegionData' is still at the main page (https://onemocneni-aktualne.mzcr.cz/covid-19) with id 'panel2-districts-regions-maps' under 'Přehled výskytu laboratorně prokázaného onemocnění COVID‑19 podle regionu' -> 'Kumulativní přehled za celé období po krajích ČR'

'recoveredByRegionData' was moved to https://onemocneni-aktualne.mzcr.cz/covid-19/prehledy-khs and its under 'Celkový počet vyléčených po onemocnění COVID‑19 v jednotlivých krajích ČR' with id 'js-total-region-recovered'
'deathsByRegionData' was also moved to https://onemocneni-aktualne.mzcr.cz/covid-19/prehledy-khs and its under 'Celkový počet úmrtí v souvislosti s onemocněním COVID‑19 v jednotlivých krajích ČR' with id 'js-total-region-died'

**Comment by zpelechova** [comment]
Hey, @stepanex , new version is out with region info 👍 .
