### ISSUE TITLE
VietNam - how to get statistics for each province

### ISSUE THREAD

**Issue by phuocantd** [apify/covid-19#211]
How to get statistics for each province? what is the api support? thanks

**Comment by zpelechova** [comment]
Hi, let me check, I think it can  be easily done.

**Comment by zpelechova** [comment]
Hey, I added it to the actor so it is now in the API. Can you check if it is what you wanted? @phuocantd

**Comment by phuocantd** [comment]
Thank you so much

**Comment by zpelechova** [comment]
Great, I was happy to help :)
