### ISSUE TITLE
Malaysia's API late to update

### ISSUE THREAD

**Issue by yaboikyleee** [apify/covid-19#244]
Hey there, some issue's with the Malaysia Covic-19 API. 
Even if its source page (http://www.moh.gov.my/index.php/pages/view/2019-ncov-wuhan) updates, the API will not update (even after 5 minutes the "link actualization") until after about an hour or two

Here's some pictures provided:

![cr1](https://user-images.githubusercontent.com/69728507/97429649-b20ad880-1952-11eb-800e-6d42ae346410.PNG)
![cr2](https://user-images.githubusercontent.com/69728507/97429654-b33c0580-1952-11eb-94c8-3c3d1bf0744c.PNG)

**Comment by zpelechova** [comment]
Hey, can you tell me more about it? I just checked and the data is the same on the webpage and in the API. Is there a specific time of the day when this happens? Or do you mean just the lastUpdatedAtSource time?

**Comment by yaboikyleee** [comment]
Hey! Thanks for reaching back. 
There isnt a issue with the Data, is more of the updating issue, it does update but after about an hour or so of the Data on the website to update.

**Comment by zpelechova** [comment]
Hey, sorry, I missed your answer, does the problem still lasts?

**Comment by yaboikyleee** [comment]
> Hey, sorry, I missed your answer, does the problem still lasts?

All good now, Thanks.
