### ISSUE TITLE
Malaysia API didn't update since 22/11/2020

### ISSUE THREAD

**Issue by Jasperang** [apify/covid-19#262]
Hey! The statistics from the covid-19 stats in Malaysia have stopped updating since the 22th of November 2020. can this be amended somehow? 

Thank you :)

**Comment by Jasperang** [comment]
It also seems like recovered's value is deceased's value and deceased's value is new local cases.

**Comment by zpelechova** [comment]
Hey, sorry for the inconevience, I have a tight deadline on another project, will fix asap. Or you can create a pull request if you knwo your way around the code.

**Comment by zpelechova** [comment]
Hey, so it shgould be fixed: https://api.apify.com/v2/datasets/drTXSjcFSebZidAJf/items?format=json&clean=1, let me know if there is any problem.
