### ISSUE TITLE
For UK covid cases the lastUpdatedAtSource has not updated since 23/12/2020

### ISSUE THREAD

**Issue by gaz-williams** [apify/covid-19#274]
From this URL https://api.apify.com/v2/key-value-stores/KWLojgM5r1JmMW4b4/records/LATEST?disableRedirect=true
The lastUpdatedAtSource has not updated the date since 23/12/2020 despite the other values updating each day.

**Comment by zpelechova** [comment]
Thanks for pointing it out. We will check it.

**Comment by katacek** [comment]
Fixed by https://github.com/apify/covid-19/pull/281
