### ISSUE TITLE
For Lithuania covid cases has not updated since 30/12/2020

### ISSUE THREAD

**Issue by gitomhub** [apify/covid-19#278]
Not working... :-(

URL https://api.apify.com/v2/key-value-stores/xhGDb8VTqjtm1AQL6/records/LATEST?disableRedirect=true

latest data is from 30/12/2020

"lastUpdatedAtApify": "2020-12-30T11:30:00.000Z",

**Comment by zpelechova** [comment]
Just updated the code. You can submit pull request next time it is not working, it is usually much faster then :)

**Comment by gitomhub** [comment]
Not working again... :-(
latest data is from 04/01/2021
"lastUpdatedAtApify": "2021-01-04T07:40:00.000Z",

**Comment by zpelechova** [comment]
Fixed today.
