### ISSUE TITLE
Wrong numbers for 100000

### ISSUE THREAD

**Issue by a6m2go** [apify/covid-19#283]
It looks like (on an external website using this code), that the number of corona cases per 100000 is not correct in cantons of Lucern, Obwalden, Schwyz, and Glarus. The absolute numbers seems to be correct through. When I compare it with the official Swiss statistics on [https://www.covid19.admin.ch/en/epidemiologic/case?detTime=total] it looks like that these four cantons have 10x less cases per 100000, then as suggested by this code. It might be an error of reading decimal digits.

**Comment by zpelechova** [comment]
Hey, we are taking the data from XLS from here https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/situation-schweiz-und-international.html, and it seems fine, can you recheck?
