### ISSUE TITLE
API for Poland

### ISSUE THREAD

**Issue by hubertgaw** [apify/covid-19#286]
Covid numbers from Poland had not beed updated since 20.01

**Comment by hubertgaw** [comment]
That is link to API: https://api.apify.com/v2/key-value-stores/3Po6TV7wTht4vIEid/records/LATEST?disableRedirect=true

**Comment by zpelechova** [comment]
Hi, we are working on it. If you can code and fix it I will merge your PR.

**Comment by hubertgaw** [comment]
I can try, but I am not very good familiar with JS so I am not sure I will fix it

**Comment by zpelechova** [comment]
Sorry it took so long, but done!
