### ISSUE TITLE
New API for Poland

### ISSUE THREAD

**Issue by xCeLeSx** [apify/covid-19#291]
Hi,

Polish governement changed API and design of information about Covid19 statistics.
You will find more information but it destroyed this API :(

**Comment by zpelechova** [comment]
Hey, and how is it working? I noticed, but doesn't seem to be able to get past this: 
![image](https://user-images.githubusercontent.com/39551460/109471764-83704c00-7a71-11eb-8b01-267b56b2dd3f.png) Is it this url? https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2?

**Comment by zpelechova** [comment]
Done, it reappeared :)
