### ISSUE TITLE
New API for Poland (Vaccinations Data)

### ISSUE THREAD

**Issue by harad1** [apify/covid-19#297]
On the current website of [Apify](https://apify.com/covid-19), the API for Poland's Covid-19 data links to the number of infections and the regions (voivodeships) most affected et cetera. 

I can't logically explain why, but the Ministry of Health decided to have a completely separate page for data regarding Covid-19 vaccinations. 

The link to the Covid-19 vaccinations data is:
[https://www.gov.pl/web/szczepimysie/raport-szczepien-przeciwko-covid-19](https://www.gov.pl/web/szczepimysie/raport-szczepien-przeciwko-covid-19).

It would be immensely helpful if you could add an API that scraps the vaccinations data under the link provided. 
Thank you 🙏 .

**Comment by zpelechova** [comment]
Hey, this is a bit out of scope of our project, but I can think of two solutions:
1) if you are a coder, you can add it as PR yourself and we will run it together with the other code.
2) if you are not a coder and you need it for a project of yours, order a custom project on our marketplace: https://apify.com/marketplace.
