### ISSUE TITLE
FIX: czechia infectedByRegion

### ISSUE THREAD

**Issue by stepanex** [apify/covid-19#305]
Czechia:infectedByRegion changed its id and was commented out in https://github.com/apify/covid-19/commit/aad0d0d25d0b5188dcacde7cb94f009be9044bd2
I tried fixing it in https://github.com/apify/covid-19/pull/304, it should work but I couldn't test it out.

**Comment by stepanex** [comment]
@zpelechova could you check it out please? thanks

**Comment by zpelechova** [comment]
I did, merged and now it is running with it.
