### ISSUE TITLE
Polish Covid 19

### ISSUE THREAD

**Issue by Kemeroniarz** [apify/covid-19#307]
The gov.pl website has been edited. API stopped working in the case of contamination of given provinces

**Comment by zpelechova** [comment]
Hey, is it still an issue? I am looking at the latest data here: https://api.apify.com/v2/datasets/2Sn4v5JC1GfGHZfCz/items?clean=true&format=json and it seems ok. I havent checked deeply.

**Comment by Kemeroniarz** [comment]
infectedCount - This value has not changed for several days. It is an
infection province. They stand still. Perhaps due to changes in
display on gov.pl. It is also worth checking to be sure -
recoveredCount, deceasedCount

The rest works perfectly.

Greetings, thanks for contacting us!

wt., 27 kwi 2021 o 12:02 Zuzka Pelechová ***@***.***>
napisał(a):
