### ISSUE TITLE
India's active case showing as total cases  

### ISSUE THREAD

**Issue by CrisesKhaos** [apify/covid-19#310]
In the region data of India's COVID-19 [API](https://api.apify.com/v2/key-value-stores/toDWvRj1JpTXiM8FF/records/LATEST?disableRedirect=true) the regions **active** cases are displayed as **total affected**. 

[India's MOH website](https://www.mohfw.gov.in/) displays the COVID statistics in quite a confusing manner as the cases marked as _total_ are **not** the _confirmed cases_(total infected) but the current _active cases_.

**Comment by zpelechova** [comment]
Hey, in the region part you mean? I have changed it.

**Comment by CrisesKhaos** [comment]
Hey @zpelechova ,yes I was talking about the region part , thank you for fixing it so quickly!
