### ISSUE TITLE
Danish api have been moved

### ISSUE THREAD

**Issue by raag2005** [apify/covid-19#311]
the danish api have been moved from https://www.ssi.dk/sygdomme-beredskab-og-forskning/sygdomsovervaagning/c/covid19-overvaagning to https://www.sst.dk/en/english/corona-eng/status-of-the-epidemic/covid-19-updates-statistics-and-charts

**Comment by zpelechova** [comment]
Hey, we are slowly retreating from the COVID API as we hope it will be less and less needed.

**Comment by zpelechova** [comment]
Hey, so after all we got the recources to rewrite the code and it should be up and running, let me know if it works for you.
