### ISSUE TITLE
Source page/URL for Singapore is broken

### ISSUE THREAD

**Issue by melvincwng** [apify/covid-19#325]
The source page/URL to extract COVID19 related data in Singapore (https://www.moh.gov.sg/covid-19/statistics) currently is no longer showing various COVID19 relared statistics.

As a result, the API response at https://api.apify.com/v2/key-value-stores/yaPbKe9e5Et61bl7W/records/LATEST?disableRedirect=true is showing a response/object with various missing values.

Is it possible if this issue could be fixed? Perhaps by utilizing another source page/URL for data extraction?

**Comment by zpelechova** [comment]
If you can suggest a page we could use as a source of information. I can take the information from COVID Worldometer actor but we prefer to use official sources whenever possible.

**Comment by melvincwng** [comment]
@zpelechova 
Suggested page: https://covidsitrep.moh.gov.sg/

That page/URL above is obtained by firstly going to:
https://www.moh.gov.sg/covid-19/testing/situation-report-pdf

Then click on 'COVID-19 Interactive Situation Report'. 

Sources of both links/URLs are from Ministry of Health (Singapore), according to the websites.
