### ISSUE TITLE
Poland data not working since 12-09-2021

### ISSUE THREAD

**Issue by ArturSowa** [apify/covid-19#326]
Poland data not working since 12-09-2021

**Comment by zpelechova** [comment]
Hey, we are working on a fix.

**Comment by ArturSowa** [comment]
Hello, any update? Thanks!

**Comment by zpelechova** [comment]
Still working on it, seems like the information about regions are gone, so we will set it up without it.

**Comment by zpelechova** [comment]
Merged.
