### ISSUE TITLE
Poland - handleRequestFunction failed

### ISSUE THREAD

**Issue by uzdowski-design** [apify/covid-19#330]
No data is returned, on every run logs show a message:
ERROR BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://rcb-gis.maps.arcgis.com/apps/opsdashboard/index.html#/e496f00bd8b947099ff95d9e26418a2c","retryCount":1}

**Comment by zpelechova** [comment]
Hey, I guess you are talking about the region data? I added them back, but it is not a 100% reliable solution and unfortunatelly we have different priorities at the moment :(.
